language: bash
sudo: required
services: docker

before_script:
  - env | sort
  - image="shoginn/${APP}"
# prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
before_install:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
script:
# build image
  - |
    (
      docker build -t "$image" "${APP}"
      docker push shoginn/${APP}
    )
jobs:
  include:
    - env: APP=adsb-exchange
    - env: APP=adsbhub
    - env: APP=dump1090
    - env: APP=flightaware
    - env: APP=flightradar24
    - env: APP=gpsd
    - env: APP=opensky
    - env: APP=planefinder
