sudo: required
language: generic

branches:
  only:
    - master

services: 
  - docker

matrix:
  include:
    - env: APP=adsb-exchange
    - env: APP=adsbhub
    - env: APP=dump1090
    - env: APP=dump1090-fa
    - env: APP=flightaware
    - env: APP=flightradar24
    - env: APP=gpsd
    - env: APP=opensky
    - env: APP=planefinder

before_install:
  # exit on error
  - set -o errexit
  - set -o pipefail

  # Pull image to help with cache
  - docker pull "shoginn/adsb:rpi-${APP}" || true
  
  # setup QEMU
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
# build image
  -  docker build -t "shoginn/adsb:rpi-${APP}" "${APP}"
deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch:
      - master
