language: bash
sudo: required
services: docker
branches:
  only:
    - master

before_script:
  - env | sort
  - image="shoginn/adsb:rpi-${APP}"
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
# prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
script:
# build image
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" "${APP}"
      docker push "$image"
    )
jobs:
  include:
    - env: APP=adsb-exchange
    - env: APP=adsbhub
    - env: APP=dump1090
    - env: APP=dump1090-fa
    - env: APP=flightaware
    - env: APP=flightradar24
    - env: APP=gpsd
    - env: APP=opensky
    - env: APP=planefinder
