version: '3.2'

services:
  # dump1090 ##################################################################
  dump1090:
    image: shoginn/docker-ads-b-dump1090:${TAG:-latest}
    build:
      context: dump1090
      dockerfile: Dockerfile-dump1090
      cache_from:
        - shoginn/docker-ads-b-dump1090
        - shoginn/docker-ads-b-dump1090:${TAG:-latest}
      args:
        DUMP1090_VERSION: v3.7.0
        DUMP1090_GIT_HASH: a654c60d65177c7156f8010d56e308836d91f02c
        DUMP1090_TAR_HASH: d10eab3ea434ad6c8d6222f19dda89bc33325dcf64d3d45bde1e5a55d64fdf0f
    ports:
      - "30002:30002/tcp"
      - "30005:30005/tcp"
    devices:
      - "/dev/bus/usb/001/009"
    env_file:
      - variables-dump1090.env
    cap_add:
      - SYS_NICE
    restart: always

  # flightradar24 #############################################################
  flightradar24:
    image: shoginn/docker-ads-b-flightradar24:${TAG:-latest}
    build:
      context: flightradar24
      dockerfile: Dockerfile-flightradar24
      cache_from:
        - shoginn/docker-ads-b-flightradar24
        - shoginn/docker-ads-b-flightradar24:${TAG:-latest}
      args:
        FR24FEED_VERSION: 1.0.23-8
        FR24FEED_HASH: adc72b6a5ffe0eb089748cd26a981eac7468b5a61ee0783c7e3bc3c0ee9c52b4
    ports:
      - "8754:8754/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-flightradar24.env
    restart: always
  
  # planefinder ###############################################################
  planefinder:
    image: shoginn/docker-ads-b-planefinder:${TAG:-latest}
    build:
      context: planefinder
      dockerfile: Dockerfile-planefinder
      cache_from:
        - shoginn/docker-ads-b-planefinder
        - shoginn/docker-ads-b-planefinder:${TAG:-latest}
      args:
        PFCLIENT_VERSION: 4.1.1
        PFCLIENT_HASH: c2411ca2c9ce1a6a00c1c8af0ce3f7f9
    ports:
      - "30053:30053/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-planefinder.env
    restart: always

  # adsbexchange-mlat #########################################################
  adsbexchange-mlat:
    image: shoginn/docker-ads-b-adsbexchange-mlat:${TAG:-latest}
    build:
      context: adsbexchange-mlat
      dockerfile: Dockerfile-adsbexchange-mlat
      cache_from:
        - shoginn/docker-ads-b-adsbexchange-mlat
        - shoginn/docker-ads-b-adsbexchange-mlat:${TAG:-latest}
      args:
        MLAT_CLIENT_VERSION: 3c3538b53363f5e0bf4271cef20be4cea79d052f
        MLAT_CLIENT_HASH: 31d64bb26e550632e45d7107ff766573fcc5c28ee014462d866420b810b57910
    ports:
      - "30104:30104/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-adsbexchange-mlat.env
    restart: always

  # adsbhub ###################################################################
  adsbhub:
    image: shoginn/docker-ads-b-adsbhub:${TAG:-latest}
    build:
      context: adsbhub
      dockerfile: Dockerfile-adsbhub
      cache_from:
        - shoginn/docker-ads-b-adsbhub
        - shoginn/docker-ads-b-adsbhub:${TAG:-latest}
    depends_on:
      - dump1090
    env_file:
      - variables-adsbhub.env
    restart: always

  # openskynetwork ############################################################
  openskynetwork:
    image: shoginn/docker-ads-b-openskynetwork:${TAG:-latest}
    build:
      context: openskynetwork
      dockerfile: Dockerfile-openskynetwork
      cache_from:
        - shoginn/docker-ads-b-openskynetwork
        - shoginn/docker-ads-b-openskynetwork:${TAG:-latest}
    depends_on:
      - dump1090
    env_file:
      - variables-openskynetwork.env
    restart: always

  # flightaware ###############################################################
  flightaware:
    image: shoginn/docker-ads-b-flightaware:${TAG:-latest}
    build:
      context: flightaware
      dockerfile: Dockerfile-flightaware
      cache_from:
        - shoginn/docker-ads-b-flightaware
        - shoginn/docker-ads-b-flightaware:${TAG:-latest}
      args:
        PIAWARE_VERSION: 3.7.0
        PIAWARE_HASH: e1c4b6955a189f58a4e10b66a2fc8a27b7ac07333cc20393ed420a2902532c8e
    ports:
      - "30105:30105/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-flightaware.env
    restart: always
