version: '3.6'

services:
  # dump1090 ##################################################################
  dump1090-fa:
    image: shoginn/docker-ads-b-dump1090-fa:${TAG:-latest}
    build:
      context: dump1090-fa
      dockerfile: Dockerfile-dump1090-fa
      cache_from:
        - shoginn/docker-ads-b-dump1090-fa
        - shoginn/docker-ads-b-dump1090-fa:${TAG:-latest}
      args:
        DUMP1090_VERSION: v3.6.3
        DUMP1090_GIT_HASH: cdba7566fde1ab45186f2dc4ea53e0594de484b1
        DUMP1090_TAR_HASH: 80aa0d3d5cfa40dad1e579f2320c0e884145862acff28b3e1da3b99a811f4810
    #ports:
    #  - "30002:30002/tcp"
    #  - "30005:30005/tcp"
    devices:
      - "/dev/bus/usb/001/009"
    env_file:
      - variables-dump1090.env
    cap_add:
      - SYS_NICE
    deploy:
      mode: global
      restart_policy:
        condition: always
        delay: 5s

  # flightradar24 #############################################################
  flightradar24:
    image: shoginn/docker-ads-b-flightradar24:${TAG:-latest}
    build:
      context: flightradar24
      dockerfile: Dockerfile-flightradar24
      cache_from:
        - shoginn/docker-ads-b-flightradar24
        - shoginn/docker-ads-b-flightradar24:${TAG:-latest}
      args:
        FR24FEED_VERSION: 1.0.23-8
        FR24FEED_HASH: adc72b6a5ffe0eb089748cd26a981eac7468b5a61ee0783c7e3bc3c0ee9c52b4
    ports:
      - "8754:8754/tcp"
    depends_on:
      - dump1090-fa
    env_file:
      - variables-flightradar24.env
    deploy:
      mode: global
      restart_policy:
        condition: always
        delay: 5s
  
  # planefinder ###############################################################
  planefinder:
    image: shoginn/docker-ads-b-planefinder:${TAG:-latest}
    build:
      context: planefinder
      dockerfile: Dockerfile-planefinder
      cache_from:
        - shoginn/docker-ads-b-planefinder
        - shoginn/docker-ads-b-planefinder:${TAG:-latest}
      args:
        PFCLIENT_VERSION: 4.1.1
        PFCLIENT_HASH: c2411ca2c9ce1a6a00c1c8af0ce3f7f9
    ports:
      - "30053:30053/tcp"
    depends_on:
      - dump1090-fa
    env_file:
      - variables-planefinder.env
    deploy:
      mode: global
      restart_policy:
        condition: always
        delay: 5s

  # adsbexchange-mlat #########################################################
  adsbexchange-mlat:
    image: shoginn/docker-ads-b-adsbexchange-mlat:${TAG:-latest}
    build:
      context: adsbexchange-mlat
      dockerfile: Dockerfile-adsbexchange-mlat
      cache_from:
        - shoginn/docker-ads-b-adsbexchange-mlat
        - shoginn/docker-ads-b-adsbexchange-mlat:${TAG:-latest}
      args:
        MLAT_CLIENT_VERSION: 3c3538b53363f5e0bf4271cef20be4cea79d052f
        MLAT_CLIENT_HASH: 31d64bb26e550632e45d7107ff766573fcc5c28ee014462d866420b810b57910
    ports:
      - "30104:30104/tcp"
    depends_on:
      - dump1090-fa
    env_file:
      - variables-adsbexchange-mlat.env
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  # adsbhub ###################################################################
  adsbhub:
    image: shoginn/docker-ads-b-adsbhub:${TAG:-latest}
    build:
      context: adsbhub
      dockerfile: Dockerfile-adsbhub
      cache_from:
        - shoginn/docker-ads-b-adsbhub
        - shoginn/docker-ads-b-adsbhub:${TAG:-latest}
    depends_on:
      - dump1090-fa
    env_file:
      - variables-adsbhub.env
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  # openskynetwork ############################################################
  openskynetwork:
    image: shoginn/docker-ads-b-openskynetwork:${TAG:-latest}
    build:
      context: openskynetwork
      dockerfile: Dockerfile-openskynetwork
      cache_from:
        - shoginn/docker-ads-b-openskynetwork
        - shoginn/docker-ads-b-openskynetwork:${TAG:-latest}
    depends_on:
      - dump1090-fa
    env_file:
      - variables-openskynetwork.env
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  # flightaware ###############################################################
  flightaware:
    image: shoginn/docker-ads-b-flightaware:${TAG:-latest}
    build:
      context: flightaware
      dockerfile: Dockerfile-flightaware
      cache_from:
        - shoginn/docker-ads-b-flightaware
        - shoginn/docker-ads-b-flightaware:${TAG:-latest}
      args:
        TCLLAUNCHER_VERSION: v1.8
        TCLLAUNCHER_HASH: f2afbf74e11a40501373099684766731dd59dfc2b9c85ba04892e6cdb2435f72
        FAUP1090_VERSION: v3.6.3
        FAUP1090_HASH: 5edf3ffce3f1336b27c869d5a031a513f6abb834215c249269fbbcf3356c5caa
        MLAT_CLIENT_VERSION: 3c3538b53363f5e0bf4271cef20be4cea79d052f
        MLAT_CLIENT_HASH: 31d64bb26e550632e45d7107ff766573fcc5c28ee014462d866420b810b57910
        PIAWARE_VERSION: v3.6.3
        PIAWARE_HASH: d5b31103cb09b79d49674558f6d1a3eaa9a297db99e3cfd5aa98733017adc337
    ports:
      - "30105:30105/tcp"
    depends_on:
      - dump1090-fa
    env_file:
      - variables-flightaware.env
    deploy:
      restart_policy:
        condition: always
        delay: 5s
